[colors]
[colors.primary]
background = '#ffffff'
foreground = '#1a1a1a'

[colors.normal]
black = '#1a1a1a'
red = '#d1383d'
green = '#3d9a57'
yellow = '#b0851f'
blue = '#318795'
magenta = '#c94d24'
cyan = '#318795'
white = '#ffffff'

[colors.bright]
black = '#8a8a8a'
red = '#d1383d'
green = '#3d9a57'
yellow = '#b0851f'
blue = '#318795'
magenta = '#c94d24'
cyan = '#318795'
white = '#ffffff'
