[colors]
[colors.primary]
background = '#0c0e13'
foreground = '#eeeeee'

[colors.normal]
black = '#161a22'
red = '#e06c75'
green = '#6ba1e6'
yellow = '#e5c07b'
blue = '#6ba1e6'
magenta = '#EE7948'
cyan = '#56b6c2'
white = '#eeeeee'

[colors.bright]
black = '#606060'
red = '#f28b93'
green = '#8bb8f0'
yellow = '#f0d49a'
blue = '#8bb8f0'
magenta = '#f5a07a'
cyan = '#7cccd5'
white = '#ffffff'
