[colors]
[colors.primary]
background = "#0B0C16"
foreground = "#ddf7ff"

[colors.normal]
black   = "#0B0C16"
red     = "#50f872"
green   = "#4fe88f"
yellow  = "#50f7d4"
blue    = "#829dd4"
magenta = "#86a7df"
cyan    = "#7cf8f7"
white   = "#85E1FB"

[colors.bright]
black   = "#6a6e95"
red     = "#85ff9d"
green   = "#9cf7c2"
yellow  = "#a4ffec"
blue    = "#c4d2ed"
magenta = "#cddbf4"
cyan    = "#d1fffe"
white   = "#ddf7ff"

[colors.cursor]
text   = "#0B0C16"
cursor = "#ddf7ff"
