[colors]
[colors.primary]
background = "#060B1E"
foreground = "#ffcead"

[colors.normal]
black   = "#060B1E"
red     = "#ED5B5A"
green   = "#92a593"
yellow  = "#E9BB4F"
blue    = "#7d82d9"
magenta = "#c89dc1"
cyan    = "#a3bfd1"
white   = "#F99957"

[colors.bright]
black   = "#6d7db6"
red     = "#faaaa9"
green   = "#c4cfc4"
yellow  = "#f7dc9c"
blue    = "#c2c4f0"
magenta = "#ead7e7"
cyan    = "#dfeaf0"
white   = "#ffcead"

[colors.cursor]
text   = "#060B1E"
cursor = "#ffcead"
